name: 'Hello World'
# triggers
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs: # what to run when the properties are met
  hello: # the id
    runs-on: ubuntu-20.04

    steps: 
      - name: Hello Step
        run: echo 'Hello World'
    